# Generated by Django 3.0.3 on 2020-03-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralamau',
            name='exploreJoburg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.Event'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='people',
            field=models.ManyToManyField(to='Accounts.UserALAMAU'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.School'),
        ),
    ]
