# Generated by Django 3.0.3 on 2020-03-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('Accounts', '0003_auto_20200312_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralamau',
            name='exploreJoburg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Event'),
        ),
    ]
